### ISSUE TITLE
Can we make the capture icon movable?

### ISSUE THREAD

**Issue by brjichkar** [lczx/watcher#3]
If i want to make the capture icon movable like facebook chat icon, How can i do it any guideline? Can i use MovableView class in OverlayViewManager? How to achieve it. Any guideline

**Comment by lczx** [comment]
First of all, sorry if I didn't reach out to you sooner, I have had several deadlines this week and wouldn't have been able to provide a proper answer to you until now.

Unfortunately I don't use Facebook so I don't know how it handles moving of the overlay, however I see 2 ways it can be done:
- Long press and dragging (but we alterady have long press mapped to other actions);
- Adding a button in settings to show a simulation of the overlay where items can be repositioned. I would go with this solution.

Looking at the code, `OverlayViewManager` handles the logic for creating, showing and hiding the views of the overlay and it is extended by each execution mode (we currently have two). As you may have seen it also manages layout parameters (i.e. position on screen) of the views.

In order to add the moving icon functionality, a flag passed in from the service to the constructor of `OverlayViewManager` may tell it to start in "placement mode" and use dummy views that can be moved around (using `MovableView` as a reference) instead of the real working ones. When the overlay is stopped, the position is saved in the configuration and used when the real overlay is started.

The service takes the flag from its start intent, so we may add a boolean argument called `placementMode` to [OverlayServiceUtil#createStartIntent()](https://github.com/lczx/watcher/blob/35b1b2eb1ff3f7fd3b6494e2a32778ee22f33d34/src/main/kotlin/net/hax/niatool/OverlayServiceUtil.kt#L9) which can be invoked by the new button in settings.

I hope this info can help you out in adding this feature. Don't hesitate to ask me more or to make a pull request if you manage to implement it. If you prefer I can even try to do it myself, but don't expect it by the end of this week.

**Comment by brjichkar** [comment]
Thanks for Details response. I will look into it and update you soon hopefully with Pull request.
